language: objective-c
before_install:
#  - brew update
#  - brew upgrade xctool
  - gem install cocoapods
before_script:
  - export QINIU_TEST_ENV="travis"
script:
  - xctool -workspace HappyDNS.xcworkspace -scheme "HappyDNS iOS" -sdk iphonesimulator -configuration Release test -test-sdk iphonesimulator7.0 -freshInstall -freshSimulator
  - xctool -workspace HappyDNS.xcworkspace -scheme "HappyDNS Mac" -sdk macosx -configuration Release test -test-sdk macosx
